### ISSUE TITLE
Makefile: "docker compose" is "docker-compose" on Fedora

### ISSUE THREAD

**Issue by aklapper** [bd808/developer-portal#1]
Following the instructions in `README.md` on Fedora 35 using `moby-engine-20.10.9-1` and `docker-compose-1.29.2-3`:
* Running `docker compose up --build --detach` triggers `unknown flag: --build`; replacing all `docker compose` with `docker-compose` in `Makefile` helps.
* `make start` triggers several `Permission denied` errors in `urllib3` and `requests`; using `sudo make start` helps.
* `open` does not exist, using `xdg-open` helps.

Just putting here in case anyone else uses such systems. Not convinced any of these are worth to get handled/"fixed" though; feel free to simply close.

**Comment by bd808** [comment]
* `docker compose` is Docker Compose v2.x. We can switch to the `docker-compose` 1.x naming without any material difference for this project.
* `make start` needing sudo sounds like a volume mount permissions issue similar to https://phabricator.wikimedia.org/T295318 for Toolhub. That was a new learning for me that the Docker volume drivers for MacOS and Linux work so differently. We can fix this project up to be more readily cross-platform.
* I knew that `open` was a MacOS-ism. The cross-platform description would be just to tell folks to open the URL in their browser of choice.

**Comment by bd808** [comment]
@aklapper I think that 2355bcc should fix the issues you have found in cross-platform support. Please do reopen or create new issue if I have not quite succeeded yet in making things work for you.
